### ISSUE TITLE
Can't update simulation description and name on summary page

### ISSUE THREAD

**Issue by Baguage** [vecnet/om#22]

**Comment by nr-nd** [comment]
I fixed the name updating between 'simple' and 'advanced' tabs (haven't merged it yet, though).

As for 'Description', it is separate from the xml, so if a user clicks 'Save' on the advanced tab, and then leaves the summary page completely, any change the user made to 'Description' will not be updated.

Since the user is only 'saving' the xml on the advanced tab, I will have to either change the way the advanced tab/page 'Save' works (have it save both form and xml), or, at the very least, somehow save the 'Description' on any 'Save' on the summary page. Otherwise, the user will have to understand that saving on the Advanced tab/page is only updating anything related to the xml.

**Comment by nr-nd** [comment]
Discussed internally. I will post the entire form from both tabs in order to save all changes.
